name: clustr
channels:
- defaults
dependencies:
- appnope=0.1.0=py27_0
- astropy=1.3.2=np112py27_0
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- bleach=1.5.0=py27_0
- cairo=1.14.8=0
- configparser=3.5.0=py27_0
- curl=7.52.1=0
- cycler=0.10.0=py27_0
- decorator=4.0.11=py27_0
- entrypoints=0.2.2=py27_1
- enum34=1.1.6=py27_0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- gettext=0.19.8=1
- glib=2.50.2=1
- gsl=2.2.1=0
- harfbuzz=0.9.39=2
- html5lib=0.999=py27_0
- icu=54.1=0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- jbig=2.1=0
- jinja2=2.9.6=py27_0
- jpeg=9b=0
- jsonschema=2.6.0=py27_0
- jupyter_client=5.0.1=py27_0
- jupyter_core=4.3.0=py27_0
- libffi=3.2.1=1
- libgcc=4.8.5=1
- libiconv=1.14=0
- libpng=1.6.27=0
- libtiff=4.0.6=3
- libxml2=2.9.4=0
- markupsafe=0.23=py27_2
- matplotlib=2.0.0=np112py27_0
- mistune=0.7.4=py27_0
- mkl=2017.0.1=0
- nbconvert=5.1.1=py27_0
- nbformat=4.3.0=py27_0
- ncurses=5.9=10
- notebook=5.0.0=py27_0
- numpy=1.12.1=py27_0
- openssl=1.0.2k=1
- pandoc=1.19.2.1=0
- pandocfilters=1.4.1=py27_0
- pango=1.40.3=1
- path.py=10.3.1=py27_0
- pathlib2=2.2.1=py27_0
- pcre=8.39=1
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- prompt_toolkit=1.0.14=py27_0
- ptyprocess=0.5.1=py27_0
- pygments=2.2.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2017.2=py27_0
- pyzmq=16.0.2=py27_0
- qt=5.6.2=0
- r=3.3.2=r3.3.2_0
- r-assertthat=0.1=r3.3.2_4
- r-backports=1.0.4=r3.3.2_0
- r-base=3.3.2=1
- r-base64enc=0.1_3=r3.3.2_0
- r-bh=1.62.0_1=r3.3.2_0
- r-bitops=1.0_6=r3.3.2_2
- r-boot=1.3_18=r3.3.2_0
- r-broom=0.4.1=r3.3.2_0
- r-car=2.1_4=r3.3.2_0
- r-caret=6.0_73=r3.3.2_0
- r-catools=1.17.1=r3.3.2_2
- r-class=7.3_14=r3.3.2_0
- r-cluster=2.0.5=r3.3.2_0
- r-codetools=0.2_15=r3.3.2_0
- r-colorspace=1.3_1=r3.3.2_0
- r-crayon=1.3.2=r3.3.2_0
- r-curl=2.3=r3.3.2_0
- r-data.table=1.10.0=r3.3.2_0
- r-dbi=0.5_1=r3.3.2_0
- r-dichromat=2.0_0=r3.3.2_2
- r-digest=0.6.10=r3.3.2_0
- r-dplyr=0.5.0=r3.3.2_0
- r-essentials=1.5.2=r3.3.2_0
- r-evaluate=0.10=r3.3.2_0
- r-forcats=0.1.1=r3.3.2_0
- r-foreach=1.4.3=r3.3.2_0
- r-foreign=0.8_67=r3.3.2_0
- r-formatr=1.4=r3.3.2_0
- r-ggplot2=2.2.0=r3.3.2_0
- r-gistr=0.3.6=r3.3.2_0
- r-glmnet=2.0_5=r3.3.2_0
- r-gtable=0.2.0=r3.3.2_0
- r-haven=1.0.0=r3.3.2_0
- r-hexbin=1.27.1=r3.3.2_0
- r-highr=0.6=r3.3.2_0
- r-hms=0.3=r3.3.2_0
- r-htmltools=0.3.5=r3.3.2_0
- r-htmlwidgets=0.8=r3.3.2_0
- r-httpuv=1.3.3=r3.3.2_0
- r-httr=1.2.1=r3.3.2_0
- r-irdisplay=0.4.4=r3.3.2_0
- r-irkernel=0.7.1=r3.3.2_0
- r-iterators=1.0.8=r3.3.2_0
- r-jsonlite=1.1=r3.3.2_0
- r-kernsmooth=2.23_15=r3.3.2_0
- r-knitr=1.15.1=r3.3.2_0
- r-labeling=0.3=r3.3.2_2
- r-lattice=0.20_34=r3.3.2_0
- r-lazyeval=0.2.0=r3.3.2_0
- r-lme4=1.1_12=r3.3.2_0
- r-lubridate=1.6.0=r3.3.2_0
- r-magrittr=1.5=r3.3.2_2
- r-maps=3.1.1=r3.3.2_0
- r-markdown=0.7.7=r3.3.2_2
- r-mass=7.3_45=r3.3.2_0
- r-matrix=1.2_7.1=r3.3.2_0
- r-matrixmodels=0.4_1=r3.3.2_0
- r-mgcv=1.8_16=r3.3.2_0
- r-mime=0.5=r3.3.2_0
- r-minqa=1.2.4=r3.3.2_2
- r-mnormt=1.5_5=r3.3.2_0
- r-modelmetrics=1.1.0=r3.3.2_0
- r-modelr=0.1.0=r3.3.2_0
- r-munsell=0.4.3=r3.3.2_0
- r-nlme=3.1_128=r3.3.2_0
- r-nloptr=1.0.4=r3.3.2_2
- r-nnet=7.3_12=r3.3.2_0
- r-openssl=0.9.5=r3.3.2_0
- r-pbdzmq=0.2_4=r3.3.2_0
- r-pbkrtest=0.4_6=r3.3.2_0
- r-plyr=1.8.4=r3.3.2_0
- r-pryr=0.1.2=r3.3.2_0
- r-psych=1.6.9=r3.3.2_0
- r-purrr=0.2.2=r3.3.2_0
- r-quantmod=0.4_7=r3.3.2_0
- r-quantreg=5.29=r3.3.2_0
- r-r6=2.2.0=r3.3.2_0
- r-randomforest=4.6_12=r3.3.2_0
- r-rbokeh=0.5.0=r3.3.2_0
- r-rcolorbrewer=1.1_2=r3.3.2_3
- r-rcpp=0.12.8=r3.3.2_0
- r-rcppeigen=0.3.2.9.0=r3.3.2_0
- r-readr=1.0.0=r3.3.2_0
- r-readxl=0.1.1=r3.3.2_0
- r-recommended=3.3.2=r3.3.2_0
- r-repr=0.10=r3.3.2_0
- r-reshape2=1.4.2=r3.3.2_0
- r-rmarkdown=1.3=r3.3.2_0
- r-rpart=4.1_10=r3.3.2_0
- r-rprojroot=1.1=r3.3.2_0
- r-rvest=0.3.2=r3.3.2_0
- r-scales=0.4.1=r3.3.2_0
- r-selectr=0.3_0=r3.3.2_0
- r-shiny=0.14.2=r3.3.2_0
- r-sourcetools=0.1.5=r3.3.2_0
- r-sparsem=1.74=r3.3.2_0
- r-spatial=7.3_11=r3.3.2_0
- r-stringi=1.1.2=r3.3.2_0
- r-stringr=1.1.0=r3.3.2_0
- r-survival=2.40_1=r3.3.2_0
- r-tibble=1.2=r3.3.2_0
- r-tidyr=0.6.0=r3.3.2_0
- r-tidyverse=1.0.0=r3.3.2_0
- r-ttr=0.23_1=r3.3.2_0
- r-uuid=0.1_2=r3.3.2_0
- r-xml2=1.0.0=r3.3.2_0
- r-xtable=1.8_2=r3.3.2_0
- r-xts=0.9_7=r3.3.2_2
- r-yaml=2.1.14=r3.3.2_0
- r-zoo=1.7_13=r3.3.2_0
- readline=6.2=2
- rpy2=2.8.5=py27r3.3.2_2
- scandir=1.5=py27_0
- scipy=0.19.0=np112py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- subprocess32=3.2.7=py27_0
- terminado=0.6=py27_0
- testpath=0.3=py27_0
- tk=8.5.18=0
- tornado=4.5.1=py27_0
- traitlets=4.3.2=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- xz=5.2.2=1
- zeromq=4.1.3=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - corner==2.0.0
  - ipython-genutils==0.2.0
  - jupyter-client==5.0.1
  - jupyter-core==4.3.0
  - prompt-toolkit==1.0.14
  - pypdf2==1.26.0
  - "git+https://github.com/jmeyers314/linmix.git"
prefix: /Users/devon/miniconda3/envs/clustr

